### ISSUE TITLE
[RFE] Diagram

### ISSUE THREAD

**Issue by christianh814** [redhat-cop/openshift-playbooks#107]
It would be nice if this had some sore of diagram so you can see (logically) how all the servers are laid out. Understanding that each site is "different", however, a simple diagram would look something like

3 masters
2 infra nodes
2 "worker" nodes

Correct?

**Comment by etsauer** [comment]
@christianh814 check out this PR: https://github.com/rhtconsulting/openshift-playbooks/pull/108

**Comment by dstockdreher** [comment]
This can be resolved?

**Comment by etsauer** [comment]
@dstockdreher I think so.

**Comment by christianh814** [comment]
Yes It can!

**Comment by JaredBurck** [comment]
SmartStart reference architecture images added to installation guide
