### ISSUE TITLE
RFE to Announce New Content

### ISSUE THREAD

**Issue by JaredBurck** [redhat-cop/openshift-playbooks#124]
it would be a cool enhancement to, instead of having a gitbot post, create a custom post in the travis build that would announce new content to RH Chat

**Comment by Jooho** [comment]
@JaredBurck is it a valid issue?  I am just going through whole issues to clear up.

If this is solved or no need anymore, could you close it?

**Comment by JaredBurck** [comment]
no longer needed since TravisCI is not the main build system used anymore for building and releasing the openshift-playbooks/uncontained.io websites

would still be a great idea or feature for new uncontained.io build/release pipeline
