### ISSUE TITLE
README refers to installing Ruby 2.0.0 but repo is requiring 2.3.0

### ISSUE THREAD

**Issue by grwallac** [redhat-cop/openshift-playbooks#130]
Fresh pull of repo:

> RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /home/xxx/openshift-playbooks/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'. 
ruby-2.3.0 is not installed.
To install do: 'rvm install ruby-2.3.0'

may need to update README.md

**Comment by etsauer** [comment]
#136 addresses this.

**Comment by JaredBurck** [comment]
resolved. #136 has been merged
