### ISSUE TITLE
Disabling `oc rsh`

### ISSUE THREAD

**Issue by christianh814** [redhat-cop/openshift-playbooks#134]
Currently what has to be done  is take an existing cluster role, such as edit, remove the permissions you wanted to restrict, and then create a new role. This new role could then be applied to users.

We should have a playbook with an example; like disabling `oc rsh` for instance.

**Comment by etsauer** [comment]
@christianh814 are you basically asking for a guide on creating custom roles?

**Comment by sabre1041** [comment]
@etsauer yes. I already have a starting point on this I'm working on with card in https://trello.com/c/7Waqfr66/29-create-delivery-playbook-on-custom-role-creation

**Comment by JaredBurck** [comment]
resolved with PR #137
