### ISSUE TITLE
Add a reference to JFrog Artifactory Reference Architecture

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/openshift-playbooks#146]
Add a reference to the recently released reference architecture on integrating OpenShift with JFrog Artifactory to install guide

https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/jfrog_artifactory_on_openshift_container_platform/

**Comment by JaredBurck** [comment]
closing since this issues since the JFrog Artifactory reference architecture has been removed/deleted

[1] https://blog.openshift.com/openshift-jfrog-artifactory-paas-stack/
