### ISSUE TITLE
Provision Servers Section in Install Guide is out of order

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-playbooks#151]
In this section: http://playbooks-rhtconsulting.rhcloud.com/playbooks/installation/#provision-servers

The ansible test command we run to validate connectivity from the control host to all of our node servers happens before the section where we actually add the hosts to the host groups in our inventory file. This needs to be re-ordered.

@redhat-cop/cant-contain-this

**Comment by etsauer** [comment]
Also, we have `-hosts` in the ansible command when it should be `hosts`.

**Comment by oybed** [comment]
Fixed by https://github.com/redhat-cop/openshift-playbooks/issues/170
