### ISSUE TITLE
Need to add ansible_become line to inventory sample

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-playbooks#158]
@redhat-cop/cant-contain-this

**Comment by beelandc** [comment]
Is the assumption that the sample inventory would not be using root? If so, don't we also need to add an ansible_ssh_user line with the non-root user name?

**Comment by JaredBurck** [comment]
It called out that you can change the ansible_user, however our install-guide assumes ansible_user is root for our installation purposes.
