### ISSUE TITLE
External Docker registry integration - broken link

### ISSUE THREAD

**Issue by raffian** [redhat-cop/openshift-playbooks#161]
Hi,

Was searching for how to integrate Artifactory with OpenShift 3.5 to replace internal Docker registry. Found this link but link is broken, 
http://playbooks-rhtconsulting.rhcloud.com/playbooks/operationalizing/external-docker-registry-integration.html

Did some digging and found this; is it applicable to OpenShift 3.5?
https://github.com/redhat-cop/openshift-playbooks/blob/2a7676daaf41d8752e2720e916a6843ea7f190ac/playbooks/continuous_delivery/external-docker-registry-integration.adoc

**Comment by sabre1041** [comment]
@raffian we moved the content around recently

Document can be found here: http://playbooks-rhtconsulting.rhcloud.com/playbooks/continuous_delivery/external-docker-registry-integration.html

**Comment by raffian** [comment]
Thank you!
