### ISSUE TITLE
Container runtime has invalid security settings

### ISSUE THREAD

**Issue by bit4man** [redhat-cop/openshift-playbooks#180]
When installing via "docker-compose" the resulting image fails to run with the following error:

$ docker logs 19290f64d825
There was an error while trying to write to `/opt/jekyll/.bundle/config`. It is
likely that you need to grant write permissions for that path.
Could not locate Gemfile or .bundle/ directory
There was an error while trying to write to `/opt/jekyll/.bundle/config`. It is
likely that you need to grant write permissions for that path.
Could not locate Gemfile or .bundle/ directory

**Comment by JaredBurck** [comment]
closing...we now just use 
```
docker run -u `id -u` -it -v $PWD/:/home/jekyll/src/:Z -p 4000:4000 redhatcop/jekyll-local-builder
```
