### ISSUE TITLE
Update installation guide to include installation of Docker

### ISSUE THREAD

**Issue by dstockdreher** [redhat-cop/openshift-playbooks#196]
We have what looks to be some incorrect/incomplete steps in teh install guide. 

In the Docker Storage Setup section
 We instruct to setup docker storage, but we never actually install/enable/start docker. 
 I think we need to add those steps into the guide and then reword this line

"This file will be consumed by the docker engine once it is installed by Ansible."
to something

**Comment by Jooho** [comment]
@dstockdreher @etsauer I think this issue is already solved.

This sentence is added to the installation guide.
  "This file will be consumed by the docker engine once it is installed by Ansible." 

I believe we can close this issue.(I don't have no permission to close it)
