### ISSUE TITLE
Guides on promoting images as part of CI/CD?

### ISSUE THREAD

**Issue by raffian** [redhat-cop/openshift-playbooks#213]
Looking for any guide or info detailing how to promote images across namespaces and operational OCP clusters.

**Comment by JaredBurck** [comment]
@raffian Have you seen Promoting Applications Across Environments [1] in the OpenShift docs?

What additional guidance or use-cases scenarios are you looking for more information on?

[1] https://docs.openshift.com/container-platform/latest/dev_guide/application_lifecycle/promoting_applications.html

**Comment by raffian** [comment]
@JaredBurck Is there any difference between the documentation you referenced and this [1] playbook?

http://v1.uncontained.io/playbooks/continuous_delivery/image_promotion.html

**Comment by JaredBurck** [comment]
@raffian I think there is a lot of similarities between these two docs but now the OpenShift doc has more info/details, including a Repeatable Promotion Process Using Jenkins section. The playbook [2] was originally authored to fill that gap and was prior to the official OpenShift doc [1]. There are definitely other and more advanced use-cases.

Do either of these two docs help with what you were looking for?  What else would you like to see in either of these documents?

[1] https://docs.openshift.com/container-platform/latest/dev_guide/application_lifecycle/promoting_applications.html
[2] http://v1.uncontained.io/playbooks/continuous_delivery/image_promotion.html

**Comment by raffian** [comment]
@JaredBurck I see the difference now, thank you, I'll go with the updated guide.

**Comment by raffian** [comment]
@JaredBurck  Pardon my ignorance, just learning the ropes on this, but something does not make sense to me. In the product documentation, step 2 from this section [1] shows the use of `oc apply` for promoting applications from one environment to another. For instance, these commands are detailed in that section for exporting the source config by label into `export.yaml`

```
$ oc login <source_environment>
$ oc project <source_project>
$ oc export dc,is,svc,route,secret,sa -l label=<application_template_name> -o yaml > export.yaml
$ oc login <target_environment>
$ oc <target_project>
```
...then running the following command to merge changes into the destination objects to complete the promotion; the documentation calls this out as a "three-way merge", but I fail to see how that's happening. We tried this approach when deploying an image from "dev" to "qa" project, so we need to update the image tag referenced in the deployment config for the changes to get picked up, but where do we provide the updated image tag to complete the merge? The command detailed in the docs has just one input:

`oc apply -f export.yaml`

[1] - https://docs.openshift.com/container-platform/3.6/dev_guide/application_lifecycle/promoting_applications.html#dev-guide-promoting-applications-repeatable-process

**Comment by lpsantil** [comment]
The docs have (just above your link):

iii. Tag your application’s image to the destination registry’s location, updating namespace, name, and tag as needed to conform to the destination staging environment:

`$ docker tag <src_env_registry_ip>:<port>/<namespace>/<image name>:<tag> <dest_env_registry_ip>:<port>/<namespace>/<image name>:<tag>`
