### ISSUE TITLE
Fluentd logging link broken

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/openshift-playbooks#33]
The link on the [logging document](https://github.com/rhtconsulting/openshift-playbooks/blob/master/playbooks/installation/logging.adoc) is currently broken. The reference refers to a path one level higher rather than at the same level as it exists today

**Comment by beelandc** [comment]
Is this still a valid bug? If so, can you clarify what you mean?

**Comment by Jooho** [comment]
@sabre1041 @beelandc I checked all links and every link are working well.

As @beelandc mentioned, we can close this issue. Could you(@sabre1041 ) close it?

**Comment by sabre1041** [comment]
@beelandc @Jooho closing issue
