### ISSUE TITLE
Need "Feedback Request" blocks to fill in CI index page (or rework of the page)

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/openshift-playbooks#42]
The Empty headers on this page are an eyesore.

http://playbooks-rhtconsulting.rhcloud.com/playbooks/continuous_delivery/

What should we do for this?

/cc @sabre1041 @trevorquinn

**Comment by sabre1041** [comment]
@etsauer has this been resolved?

**Comment by goern** [comment]
Hey all, I will write up some stuff for this topic, happy to feed it to you too.

/cc @sabre1041 @trevorquinn @aweiteka

**Comment by JaredBurck** [comment]
Content created for:
- Application Promotion
- Integration with External Systems

Remove empty headers until content is published:
- Application Builds
- Application Deployments
